// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentJobManagement.Data;

#nullable disable

namespace StudentJobManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006033332_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentJobManagement.Models.HocNangCao", b =>
                {
                    b.Property<int>("MaHNC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHNC"));

                    b.Property<string>("BacHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHNC");

                    b.HasIndex("MaSV");

                    b.ToTable("HOC_NANG_CAO");
                });

            modelBuilder.Entity("StudentJobManagement.Models.LinhVuc", b =>
                {
                    b.Property<string>("MaLinhVuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLinhVuc");

                    b.ToTable("LINH_VUC");
                });

            modelBuilder.Entity("StudentJobManagement.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLinhVuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNganh");

                    b.HasIndex("MaLinhVuc");

                    b.ToTable("NGANH_HOC");
                });

            modelBuilder.Entity("StudentJobManagement.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NamTotNghiep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XepLoaiTN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaNganh");

                    b.ToTable("SINH_VIEN");
                });

            modelBuilder.Entity("StudentJobManagement.Models.ViecLamSV", b =>
                {
                    b.Property<int>("MaViecLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaViecLam"));

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DungNganh")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MucLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCongTy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaViecLam");

                    b.HasIndex("MaSV");

                    b.ToTable("VIEC_LAM_SV");
                });

            modelBuilder.Entity("StudentJobManagement.Models.HocNangCao", b =>
                {
                    b.HasOne("StudentJobManagement.Models.SinhVien", "SinhVien")
                        .WithMany("HocNangCaos")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentJobManagement.Models.NganhHoc", b =>
                {
                    b.HasOne("StudentJobManagement.Models.LinhVuc", "LinhVuc")
                        .WithMany("NganhHocs")
                        .HasForeignKey("MaLinhVuc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinhVuc");
                });

            modelBuilder.Entity("StudentJobManagement.Models.SinhVien", b =>
                {
                    b.HasOne("StudentJobManagement.Models.NganhHoc", "NganhHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("StudentJobManagement.Models.ViecLamSV", b =>
                {
                    b.HasOne("StudentJobManagement.Models.SinhVien", "SinhVien")
                        .WithMany("ViecLams")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentJobManagement.Models.LinhVuc", b =>
                {
                    b.Navigation("NganhHocs");
                });

            modelBuilder.Entity("StudentJobManagement.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("StudentJobManagement.Models.SinhVien", b =>
                {
                    b.Navigation("HocNangCaos");

                    b.Navigation("ViecLams");
                });
#pragma warning restore 612, 618
        }
    }
}
